/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SwDotjsRouteImport } from './routes/sw[.]js'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapStaticDotxmlRouteImport } from './routes/sitemap-static[.]xml'
import { Route as SitemapSpecialtiesDotxmlRouteImport } from './routes/sitemap-specialties[.]xml'
import { Route as SitemapDoctorsDotxmlRouteImport } from './routes/sitemap-doctors[.]xml'
import { Route as SitemapArticlesDotxmlRouteImport } from './routes/sitemap-articles[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PayRouteImport } from './routes/pay'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as MissingDrugsRouteImport } from './routes/missing-drugs'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinDoctorRouteImport } from './routes/join-doctor'
import { Route as IndexnowKeyDottxtRouteImport } from './routes/indexnow-key[.]txt'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as USlugRouteImport } from './routes/u.$slug'
import { Route as SpecialtySlugRouteImport } from './routes/specialty.$slug'
import { Route as RxIdRouteImport } from './routes/rx.$id'
import { Route as ReceiptAppointmentIdRouteImport } from './routes/receipt.$appointmentId'
import { Route as QShortIdRouteImport } from './routes/q.$shortId'
import { Route as ProfileMedicalHistoryRouteImport } from './routes/profile.medical-history'
import { Route as ProfileLabResultsRouteImport } from './routes/profile.lab-results'
import { Route as PharmacyRegisterRouteImport } from './routes/pharmacy.register'
import { Route as PharmacyDashboardRouteImport } from './routes/pharmacy.dashboard'
import { Route as MyQueueAppointmentIdRouteImport } from './routes/my-queue.$appointmentId'
import { Route as FeedNewRouteImport } from './routes/feed.new'
import { Route as DoctorVerificationRouteImport } from './routes/doctor.verification'
import { Route as DoctorSponsorshipRouteImport } from './routes/doctor.sponsorship'
import { Route as DoctorSoloRouteImport } from './routes/doctor.solo'
import { Route as DoctorFeedbackRouteImport } from './routes/doctor.feedback'
import { Route as DoctorIdRouteImport } from './routes/doctor.$id'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardPatientsRouteImport } from './routes/dashboard.patients'
import { Route as DashboardExpensesRouteImport } from './routes/dashboard.expenses'
import { Route as DashboardEarningsRouteImport } from './routes/dashboard.earnings'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as ConsultationIdRouteImport } from './routes/consultation.$id'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as AdminSupportTicketsRouteImport } from './routes/admin.support-tickets'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSubscriptionRequestsRouteImport } from './routes/admin.subscription-requests'
import { Route as AdminSeedDirectoryRouteImport } from './routes/admin.seed-directory'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminErrorsRouteImport } from './routes/admin.errors'
import { Route as AdminEmrRouteImport } from './routes/admin.emr'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as SpecialtySlugCityRouteImport } from './routes/specialty.$slug.$city'
import { Route as RxVerifyNumberRouteImport } from './routes/rx.verify.$number'
import { Route as FeedPostIdRouteImport } from './routes/feed.post.$id'
import { Route as DashboardVisitNewRouteImport } from './routes/dashboard.visit.new'
import { Route as DashboardSettingsSignatureRouteImport } from './routes/dashboard.settings.signature'
import { Route as DashboardSettingsFollowupRouteImport } from './routes/dashboard.settings.followup'
import { Route as DashboardSettingsBillingRouteImport } from './routes/dashboard.settings.billing'
import { Route as DashboardPatientIdRouteImport } from './routes/dashboard.patient.$id'
import { Route as DSlugContactDotvcfRouteImport } from './routes/d.$slug.contact[.]vcf'
import { Route as ApiPublicWebVitalsRouteImport } from './routes/api/public/web-vitals'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SwDotjsRoute = SwDotjsRouteImport.update({
  id: '/sw.js',
  path: '/sw.js',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaticDotxmlRoute = SitemapStaticDotxmlRouteImport.update({
  id: '/sitemap-static.xml',
  path: '/sitemap-static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapSpecialtiesDotxmlRoute =
  SitemapSpecialtiesDotxmlRouteImport.update({
    id: '/sitemap-specialties.xml',
    path: '/sitemap-specialties.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDoctorsDotxmlRoute = SitemapDoctorsDotxmlRouteImport.update({
  id: '/sitemap-doctors.xml',
  path: '/sitemap-doctors.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapArticlesDotxmlRoute = SitemapArticlesDotxmlRouteImport.update({
  id: '/sitemap-articles.xml',
  path: '/sitemap-articles.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const MissingDrugsRoute = MissingDrugsRouteImport.update({
  id: '/missing-drugs',
  path: '/missing-drugs',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinDoctorRoute = JoinDoctorRouteImport.update({
  id: '/join-doctor',
  path: '/join-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexnowKeyDottxtRoute = IndexnowKeyDottxtRouteImport.update({
  id: '/indexnow-key.txt',
  path: '/indexnow-key.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtySlugRoute = SpecialtySlugRouteImport.update({
  id: '/specialty/$slug',
  path: '/specialty/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RxIdRoute = RxIdRouteImport.update({
  id: '/rx/$id',
  path: '/rx/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptAppointmentIdRoute = ReceiptAppointmentIdRouteImport.update({
  id: '/receipt/$appointmentId',
  path: '/receipt/$appointmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const QShortIdRoute = QShortIdRouteImport.update({
  id: '/q/$shortId',
  path: '/q/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMedicalHistoryRoute = ProfileMedicalHistoryRouteImport.update({
  id: '/medical-history',
  path: '/medical-history',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileLabResultsRoute = ProfileLabResultsRouteImport.update({
  id: '/lab-results',
  path: '/lab-results',
  getParentRoute: () => ProfileRoute,
} as any)
const PharmacyRegisterRoute = PharmacyRegisterRouteImport.update({
  id: '/pharmacy/register',
  path: '/pharmacy/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyDashboardRoute = PharmacyDashboardRouteImport.update({
  id: '/pharmacy/dashboard',
  path: '/pharmacy/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQueueAppointmentIdRoute = MyQueueAppointmentIdRouteImport.update({
  id: '/my-queue/$appointmentId',
  path: '/my-queue/$appointmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedNewRoute = FeedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FeedRoute,
} as any)
const DoctorVerificationRoute = DoctorVerificationRouteImport.update({
  id: '/doctor/verification',
  path: '/doctor/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSponsorshipRoute = DoctorSponsorshipRouteImport.update({
  id: '/doctor/sponsorship',
  path: '/doctor/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSoloRoute = DoctorSoloRouteImport.update({
  id: '/doctor/solo',
  path: '/doctor/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorFeedbackRoute = DoctorFeedbackRouteImport.update({
  id: '/doctor/feedback',
  path: '/doctor/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIdRoute = DoctorIdRouteImport.update({
  id: '/doctor/$id',
  path: '/doctor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpensesRoute = DashboardExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEarningsRoute = DashboardEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationIdRoute = ConsultationIdRouteImport.update({
  id: '/consultation/$id',
  path: '/consultation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/admin/withdrawals',
  path: '/admin/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/admin/verifications',
  path: '/admin/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportTicketsRoute = AdminSupportTicketsRouteImport.update({
  id: '/admin/support-tickets',
  path: '/admin/support-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionRequestsRoute =
  AdminSubscriptionRequestsRouteImport.update({
    id: '/admin/subscription-requests',
    path: '/admin/subscription-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSeedDirectoryRoute = AdminSeedDirectoryRouteImport.update({
  id: '/admin/seed-directory',
  path: '/admin/seed-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/admin/errors',
  path: '/admin/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmrRoute = AdminEmrRouteImport.update({
  id: '/admin/emr',
  path: '/admin/emr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admin/admissions',
  path: '/admin/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtySlugCityRoute = SpecialtySlugCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => SpecialtySlugRoute,
} as any)
const RxVerifyNumberRoute = RxVerifyNumberRouteImport.update({
  id: '/rx/verify/$number',
  path: '/rx/verify/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedPostIdRoute = FeedPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => FeedRoute,
} as any)
const DashboardVisitNewRoute = DashboardVisitNewRouteImport.update({
  id: '/visit/new',
  path: '/visit/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsSignatureRoute =
  DashboardSettingsSignatureRouteImport.update({
    id: '/settings/signature',
    path: '/settings/signature',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsFollowupRoute =
  DashboardSettingsFollowupRouteImport.update({
    id: '/settings/followup',
    path: '/settings/followup',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientIdRoute = DashboardPatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DSlugContactDotvcfRoute = DSlugContactDotvcfRouteImport.update({
  id: '/contact.vcf',
  path: '/contact.vcf',
  getParentRoute: () => DSlugRoute,
} as any)
const ApiPublicWebVitalsRoute = ApiPublicWebVitalsRouteImport.update({
  id: '/api/public/web-vitals',
  path: '/api/public/web-vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/feed': typeof FeedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/indexnow-key.txt': typeof IndexnowKeyDottxtRoute
  '/join-doctor': typeof JoinDoctorRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/missing-drugs': typeof MissingDrugsRoute
  '/nearby': typeof NearbyRoute
  '/pay': typeof PayRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap-articles.xml': typeof SitemapArticlesDotxmlRoute
  '/sitemap-doctors.xml': typeof SitemapDoctorsDotxmlRoute
  '/sitemap-specialties.xml': typeof SitemapSpecialtiesDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sw.js': typeof SwDotjsRoute
  '/terms': typeof TermsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/emr': typeof AdminEmrRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seed-directory': typeof AdminSeedDirectoryRoute
  '/admin/subscription-requests': typeof AdminSubscriptionRequestsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support-tickets': typeof AdminSupportTicketsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/d/$slug': typeof DSlugRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/doctor/feedback': typeof DoctorFeedbackRoute
  '/doctor/solo': typeof DoctorSoloRoute
  '/doctor/sponsorship': typeof DoctorSponsorshipRoute
  '/doctor/verification': typeof DoctorVerificationRoute
  '/feed/new': typeof FeedNewRoute
  '/my-queue/$appointmentId': typeof MyQueueAppointmentIdRoute
  '/pharmacy/dashboard': typeof PharmacyDashboardRoute
  '/pharmacy/register': typeof PharmacyRegisterRoute
  '/profile/lab-results': typeof ProfileLabResultsRoute
  '/profile/medical-history': typeof ProfileMedicalHistoryRoute
  '/q/$shortId': typeof QShortIdRoute
  '/receipt/$appointmentId': typeof ReceiptAppointmentIdRoute
  '/rx/$id': typeof RxIdRoute
  '/specialty/$slug': typeof SpecialtySlugRouteWithChildren
  '/u/$slug': typeof USlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/api/public/web-vitals': typeof ApiPublicWebVitalsRoute
  '/d/$slug/contact.vcf': typeof DSlugContactDotvcfRoute
  '/dashboard/patient/$id': typeof DashboardPatientIdRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/followup': typeof DashboardSettingsFollowupRoute
  '/dashboard/settings/signature': typeof DashboardSettingsSignatureRoute
  '/dashboard/visit/new': typeof DashboardVisitNewRoute
  '/feed/post/$id': typeof FeedPostIdRoute
  '/rx/verify/$number': typeof RxVerifyNumberRoute
  '/specialty/$slug/$city': typeof SpecialtySlugCityRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/feed': typeof FeedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/indexnow-key.txt': typeof IndexnowKeyDottxtRoute
  '/join-doctor': typeof JoinDoctorRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/missing-drugs': typeof MissingDrugsRoute
  '/nearby': typeof NearbyRoute
  '/pay': typeof PayRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap-articles.xml': typeof SitemapArticlesDotxmlRoute
  '/sitemap-doctors.xml': typeof SitemapDoctorsDotxmlRoute
  '/sitemap-specialties.xml': typeof SitemapSpecialtiesDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sw.js': typeof SwDotjsRoute
  '/terms': typeof TermsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/emr': typeof AdminEmrRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seed-directory': typeof AdminSeedDirectoryRoute
  '/admin/subscription-requests': typeof AdminSubscriptionRequestsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support-tickets': typeof AdminSupportTicketsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/d/$slug': typeof DSlugRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/doctor/feedback': typeof DoctorFeedbackRoute
  '/doctor/solo': typeof DoctorSoloRoute
  '/doctor/sponsorship': typeof DoctorSponsorshipRoute
  '/doctor/verification': typeof DoctorVerificationRoute
  '/feed/new': typeof FeedNewRoute
  '/my-queue/$appointmentId': typeof MyQueueAppointmentIdRoute
  '/pharmacy/dashboard': typeof PharmacyDashboardRoute
  '/pharmacy/register': typeof PharmacyRegisterRoute
  '/profile/lab-results': typeof ProfileLabResultsRoute
  '/profile/medical-history': typeof ProfileMedicalHistoryRoute
  '/q/$shortId': typeof QShortIdRoute
  '/receipt/$appointmentId': typeof ReceiptAppointmentIdRoute
  '/rx/$id': typeof RxIdRoute
  '/specialty/$slug': typeof SpecialtySlugRouteWithChildren
  '/u/$slug': typeof USlugRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/api/public/web-vitals': typeof ApiPublicWebVitalsRoute
  '/d/$slug/contact.vcf': typeof DSlugContactDotvcfRoute
  '/dashboard/patient/$id': typeof DashboardPatientIdRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/followup': typeof DashboardSettingsFollowupRoute
  '/dashboard/settings/signature': typeof DashboardSettingsSignatureRoute
  '/dashboard/visit/new': typeof DashboardVisitNewRoute
  '/feed/post/$id': typeof FeedPostIdRoute
  '/rx/verify/$number': typeof RxVerifyNumberRoute
  '/specialty/$slug/$city': typeof SpecialtySlugCityRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/feed': typeof FeedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/indexnow-key.txt': typeof IndexnowKeyDottxtRoute
  '/join-doctor': typeof JoinDoctorRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/missing-drugs': typeof MissingDrugsRoute
  '/nearby': typeof NearbyRoute
  '/pay': typeof PayRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap-articles.xml': typeof SitemapArticlesDotxmlRoute
  '/sitemap-doctors.xml': typeof SitemapDoctorsDotxmlRoute
  '/sitemap-specialties.xml': typeof SitemapSpecialtiesDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sw.js': typeof SwDotjsRoute
  '/terms': typeof TermsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/emr': typeof AdminEmrRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seed-directory': typeof AdminSeedDirectoryRoute
  '/admin/subscription-requests': typeof AdminSubscriptionRequestsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support-tickets': typeof AdminSupportTicketsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/d/$slug': typeof DSlugRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/doctor/feedback': typeof DoctorFeedbackRoute
  '/doctor/solo': typeof DoctorSoloRoute
  '/doctor/sponsorship': typeof DoctorSponsorshipRoute
  '/doctor/verification': typeof DoctorVerificationRoute
  '/feed/new': typeof FeedNewRoute
  '/my-queue/$appointmentId': typeof MyQueueAppointmentIdRoute
  '/pharmacy/dashboard': typeof PharmacyDashboardRoute
  '/pharmacy/register': typeof PharmacyRegisterRoute
  '/profile/lab-results': typeof ProfileLabResultsRoute
  '/profile/medical-history': typeof ProfileMedicalHistoryRoute
  '/q/$shortId': typeof QShortIdRoute
  '/receipt/$appointmentId': typeof ReceiptAppointmentIdRoute
  '/rx/$id': typeof RxIdRoute
  '/specialty/$slug': typeof SpecialtySlugRouteWithChildren
  '/u/$slug': typeof USlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/api/public/web-vitals': typeof ApiPublicWebVitalsRoute
  '/d/$slug/contact.vcf': typeof DSlugContactDotvcfRoute
  '/dashboard/patient/$id': typeof DashboardPatientIdRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/followup': typeof DashboardSettingsFollowupRoute
  '/dashboard/settings/signature': typeof DashboardSettingsSignatureRoute
  '/dashboard/visit/new': typeof DashboardVisitNewRoute
  '/feed/post/$id': typeof FeedPostIdRoute
  '/rx/verify/$number': typeof RxVerifyNumberRoute
  '/specialty/$slug/$city': typeof SpecialtySlugCityRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointments'
    | '/billing'
    | '/contact'
    | '/dashboard'
    | '/doctors'
    | '/feed'
    | '/forgot-password'
    | '/how-it-works'
    | '/indexnow-key.txt'
    | '/join-doctor'
    | '/login'
    | '/manifest.webmanifest'
    | '/missing-drugs'
    | '/nearby'
    | '/pay'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap-articles.xml'
    | '/sitemap-doctors.xml'
    | '/sitemap-specialties.xml'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/sw.js'
    | '/terms'
    | '/admin/admissions'
    | '/admin/articles'
    | '/admin/billing'
    | '/admin/doctors'
    | '/admin/documents'
    | '/admin/emr'
    | '/admin/errors'
    | '/admin/inventory'
    | '/admin/patients'
    | '/admin/reviews'
    | '/admin/seed-directory'
    | '/admin/subscription-requests'
    | '/admin/subscriptions'
    | '/admin/support-tickets'
    | '/admin/verifications'
    | '/admin/withdrawals'
    | '/articles/$slug'
    | '/auth/callback'
    | '/checkout/return'
    | '/claim/$token'
    | '/consultation/$id'
    | '/d/$slug'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/expenses'
    | '/dashboard/patients'
    | '/dashboard/reviews'
    | '/dashboard/support'
    | '/doctor/$id'
    | '/doctor/feedback'
    | '/doctor/solo'
    | '/doctor/sponsorship'
    | '/doctor/verification'
    | '/feed/new'
    | '/my-queue/$appointmentId'
    | '/pharmacy/dashboard'
    | '/pharmacy/register'
    | '/profile/lab-results'
    | '/profile/medical-history'
    | '/q/$shortId'
    | '/receipt/$appointmentId'
    | '/rx/$id'
    | '/specialty/$slug'
    | '/u/$slug'
    | '/admin/'
    | '/articles/'
    | '/api/public/web-vitals'
    | '/d/$slug/contact.vcf'
    | '/dashboard/patient/$id'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/followup'
    | '/dashboard/settings/signature'
    | '/dashboard/visit/new'
    | '/feed/post/$id'
    | '/rx/verify/$number'
    | '/specialty/$slug/$city'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointments'
    | '/billing'
    | '/contact'
    | '/dashboard'
    | '/doctors'
    | '/feed'
    | '/forgot-password'
    | '/how-it-works'
    | '/indexnow-key.txt'
    | '/join-doctor'
    | '/login'
    | '/manifest.webmanifest'
    | '/missing-drugs'
    | '/nearby'
    | '/pay'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap-articles.xml'
    | '/sitemap-doctors.xml'
    | '/sitemap-specialties.xml'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/sw.js'
    | '/terms'
    | '/admin/admissions'
    | '/admin/articles'
    | '/admin/billing'
    | '/admin/doctors'
    | '/admin/documents'
    | '/admin/emr'
    | '/admin/errors'
    | '/admin/inventory'
    | '/admin/patients'
    | '/admin/reviews'
    | '/admin/seed-directory'
    | '/admin/subscription-requests'
    | '/admin/subscriptions'
    | '/admin/support-tickets'
    | '/admin/verifications'
    | '/admin/withdrawals'
    | '/articles/$slug'
    | '/auth/callback'
    | '/checkout/return'
    | '/claim/$token'
    | '/consultation/$id'
    | '/d/$slug'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/expenses'
    | '/dashboard/patients'
    | '/dashboard/reviews'
    | '/dashboard/support'
    | '/doctor/$id'
    | '/doctor/feedback'
    | '/doctor/solo'
    | '/doctor/sponsorship'
    | '/doctor/verification'
    | '/feed/new'
    | '/my-queue/$appointmentId'
    | '/pharmacy/dashboard'
    | '/pharmacy/register'
    | '/profile/lab-results'
    | '/profile/medical-history'
    | '/q/$shortId'
    | '/receipt/$appointmentId'
    | '/rx/$id'
    | '/specialty/$slug'
    | '/u/$slug'
    | '/admin'
    | '/articles'
    | '/api/public/web-vitals'
    | '/d/$slug/contact.vcf'
    | '/dashboard/patient/$id'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/followup'
    | '/dashboard/settings/signature'
    | '/dashboard/visit/new'
    | '/feed/post/$id'
    | '/rx/verify/$number'
    | '/specialty/$slug/$city'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointments'
    | '/billing'
    | '/contact'
    | '/dashboard'
    | '/doctors'
    | '/feed'
    | '/forgot-password'
    | '/how-it-works'
    | '/indexnow-key.txt'
    | '/join-doctor'
    | '/login'
    | '/manifest.webmanifest'
    | '/missing-drugs'
    | '/nearby'
    | '/pay'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap-articles.xml'
    | '/sitemap-doctors.xml'
    | '/sitemap-specialties.xml'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/sw.js'
    | '/terms'
    | '/admin/admissions'
    | '/admin/articles'
    | '/admin/billing'
    | '/admin/doctors'
    | '/admin/documents'
    | '/admin/emr'
    | '/admin/errors'
    | '/admin/inventory'
    | '/admin/patients'
    | '/admin/reviews'
    | '/admin/seed-directory'
    | '/admin/subscription-requests'
    | '/admin/subscriptions'
    | '/admin/support-tickets'
    | '/admin/verifications'
    | '/admin/withdrawals'
    | '/articles/$slug'
    | '/auth/callback'
    | '/checkout/return'
    | '/claim/$token'
    | '/consultation/$id'
    | '/d/$slug'
    | '/dashboard/analytics'
    | '/dashboard/earnings'
    | '/dashboard/expenses'
    | '/dashboard/patients'
    | '/dashboard/reviews'
    | '/dashboard/support'
    | '/doctor/$id'
    | '/doctor/feedback'
    | '/doctor/solo'
    | '/doctor/sponsorship'
    | '/doctor/verification'
    | '/feed/new'
    | '/my-queue/$appointmentId'
    | '/pharmacy/dashboard'
    | '/pharmacy/register'
    | '/profile/lab-results'
    | '/profile/medical-history'
    | '/q/$shortId'
    | '/receipt/$appointmentId'
    | '/rx/$id'
    | '/specialty/$slug'
    | '/u/$slug'
    | '/admin/'
    | '/articles/'
    | '/api/public/web-vitals'
    | '/d/$slug/contact.vcf'
    | '/dashboard/patient/$id'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/followup'
    | '/dashboard/settings/signature'
    | '/dashboard/visit/new'
    | '/feed/post/$id'
    | '/rx/verify/$number'
    | '/specialty/$slug/$city'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BillingRoute: typeof BillingRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DoctorsRoute: typeof DoctorsRoute
  FeedRoute: typeof FeedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IndexnowKeyDottxtRoute: typeof IndexnowKeyDottxtRoute
  JoinDoctorRoute: typeof JoinDoctorRoute
  LoginRoute: typeof LoginRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  MissingDrugsRoute: typeof MissingDrugsRoute
  NearbyRoute: typeof NearbyRoute
  PayRoute: typeof PayRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapArticlesDotxmlRoute: typeof SitemapArticlesDotxmlRoute
  SitemapDoctorsDotxmlRoute: typeof SitemapDoctorsDotxmlRoute
  SitemapSpecialtiesDotxmlRoute: typeof SitemapSpecialtiesDotxmlRoute
  SitemapStaticDotxmlRoute: typeof SitemapStaticDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SwDotjsRoute: typeof SwDotjsRoute
  TermsRoute: typeof TermsRoute
  AdminAdmissionsRoute: typeof AdminAdmissionsRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminEmrRoute: typeof AdminEmrRoute
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSeedDirectoryRoute: typeof AdminSeedDirectoryRoute
  AdminSubscriptionRequestsRoute: typeof AdminSubscriptionRequestsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportTicketsRoute: typeof AdminSupportTicketsRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  ConsultationIdRoute: typeof ConsultationIdRoute
  DSlugRoute: typeof DSlugRouteWithChildren
  DoctorIdRoute: typeof DoctorIdRoute
  DoctorFeedbackRoute: typeof DoctorFeedbackRoute
  DoctorSoloRoute: typeof DoctorSoloRoute
  DoctorSponsorshipRoute: typeof DoctorSponsorshipRoute
  DoctorVerificationRoute: typeof DoctorVerificationRoute
  MyQueueAppointmentIdRoute: typeof MyQueueAppointmentIdRoute
  PharmacyDashboardRoute: typeof PharmacyDashboardRoute
  PharmacyRegisterRoute: typeof PharmacyRegisterRoute
  QShortIdRoute: typeof QShortIdRoute
  ReceiptAppointmentIdRoute: typeof ReceiptAppointmentIdRoute
  RxIdRoute: typeof RxIdRoute
  SpecialtySlugRoute: typeof SpecialtySlugRouteWithChildren
  USlugRoute: typeof USlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ApiPublicWebVitalsRoute: typeof ApiPublicWebVitalsRoute
  RxVerifyNumberRoute: typeof RxVerifyNumberRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sw.js': {
      id: '/sw.js'
      path: '/sw.js'
      fullPath: '/sw.js'
      preLoaderRoute: typeof SwDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-static.xml': {
      id: '/sitemap-static.xml'
      path: '/sitemap-static.xml'
      fullPath: '/sitemap-static.xml'
      preLoaderRoute: typeof SitemapStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-specialties.xml': {
      id: '/sitemap-specialties.xml'
      path: '/sitemap-specialties.xml'
      fullPath: '/sitemap-specialties.xml'
      preLoaderRoute: typeof SitemapSpecialtiesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-doctors.xml': {
      id: '/sitemap-doctors.xml'
      path: '/sitemap-doctors.xml'
      fullPath: '/sitemap-doctors.xml'
      preLoaderRoute: typeof SitemapDoctorsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-articles.xml': {
      id: '/sitemap-articles.xml'
      path: '/sitemap-articles.xml'
      fullPath: '/sitemap-articles.xml'
      preLoaderRoute: typeof SitemapArticlesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missing-drugs': {
      id: '/missing-drugs'
      path: '/missing-drugs'
      fullPath: '/missing-drugs'
      preLoaderRoute: typeof MissingDrugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-doctor': {
      id: '/join-doctor'
      path: '/join-doctor'
      fullPath: '/join-doctor'
      preLoaderRoute: typeof JoinDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexnow-key.txt': {
      id: '/indexnow-key.txt'
      path: '/indexnow-key.txt'
      fullPath: '/indexnow-key.txt'
      preLoaderRoute: typeof IndexnowKeyDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialty/$slug': {
      id: '/specialty/$slug'
      path: '/specialty/$slug'
      fullPath: '/specialty/$slug'
      preLoaderRoute: typeof SpecialtySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rx/$id': {
      id: '/rx/$id'
      path: '/rx/$id'
      fullPath: '/rx/$id'
      preLoaderRoute: typeof RxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$appointmentId': {
      id: '/receipt/$appointmentId'
      path: '/receipt/$appointmentId'
      fullPath: '/receipt/$appointmentId'
      preLoaderRoute: typeof ReceiptAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$shortId': {
      id: '/q/$shortId'
      path: '/q/$shortId'
      fullPath: '/q/$shortId'
      preLoaderRoute: typeof QShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/medical-history': {
      id: '/profile/medical-history'
      path: '/medical-history'
      fullPath: '/profile/medical-history'
      preLoaderRoute: typeof ProfileMedicalHistoryRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/lab-results': {
      id: '/profile/lab-results'
      path: '/lab-results'
      fullPath: '/profile/lab-results'
      preLoaderRoute: typeof ProfileLabResultsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/pharmacy/register': {
      id: '/pharmacy/register'
      path: '/pharmacy/register'
      fullPath: '/pharmacy/register'
      preLoaderRoute: typeof PharmacyRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/dashboard': {
      id: '/pharmacy/dashboard'
      path: '/pharmacy/dashboard'
      fullPath: '/pharmacy/dashboard'
      preLoaderRoute: typeof PharmacyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-queue/$appointmentId': {
      id: '/my-queue/$appointmentId'
      path: '/my-queue/$appointmentId'
      fullPath: '/my-queue/$appointmentId'
      preLoaderRoute: typeof MyQueueAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/new': {
      id: '/feed/new'
      path: '/new'
      fullPath: '/feed/new'
      preLoaderRoute: typeof FeedNewRouteImport
      parentRoute: typeof FeedRoute
    }
    '/doctor/verification': {
      id: '/doctor/verification'
      path: '/doctor/verification'
      fullPath: '/doctor/verification'
      preLoaderRoute: typeof DoctorVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/sponsorship': {
      id: '/doctor/sponsorship'
      path: '/doctor/sponsorship'
      fullPath: '/doctor/sponsorship'
      preLoaderRoute: typeof DoctorSponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/solo': {
      id: '/doctor/solo'
      path: '/doctor/solo'
      fullPath: '/doctor/solo'
      preLoaderRoute: typeof DoctorSoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/feedback': {
      id: '/doctor/feedback'
      path: '/doctor/feedback'
      fullPath: '/doctor/feedback'
      preLoaderRoute: typeof DoctorFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/$id': {
      id: '/doctor/$id'
      path: '/doctor/$id'
      fullPath: '/doctor/$id'
      preLoaderRoute: typeof DoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients': {
      id: '/dashboard/patients'
      path: '/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/expenses': {
      id: '/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/earnings': {
      id: '/dashboard/earnings'
      path: '/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof DashboardEarningsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation/$id': {
      id: '/consultation/$id'
      path: '/consultation/$id'
      fullPath: '/consultation/$id'
      preLoaderRoute: typeof ConsultationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support-tickets': {
      id: '/admin/support-tickets'
      path: '/admin/support-tickets'
      fullPath: '/admin/support-tickets'
      preLoaderRoute: typeof AdminSupportTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscription-requests': {
      id: '/admin/subscription-requests'
      path: '/admin/subscription-requests'
      fullPath: '/admin/subscription-requests'
      preLoaderRoute: typeof AdminSubscriptionRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seed-directory': {
      id: '/admin/seed-directory'
      path: '/admin/seed-directory'
      fullPath: '/admin/seed-directory'
      preLoaderRoute: typeof AdminSeedDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/errors': {
      id: '/admin/errors'
      path: '/admin/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emr': {
      id: '/admin/emr'
      path: '/admin/emr'
      fullPath: '/admin/emr'
      preLoaderRoute: typeof AdminEmrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admin/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialty/$slug/$city': {
      id: '/specialty/$slug/$city'
      path: '/$city'
      fullPath: '/specialty/$slug/$city'
      preLoaderRoute: typeof SpecialtySlugCityRouteImport
      parentRoute: typeof SpecialtySlugRoute
    }
    '/rx/verify/$number': {
      id: '/rx/verify/$number'
      path: '/rx/verify/$number'
      fullPath: '/rx/verify/$number'
      preLoaderRoute: typeof RxVerifyNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/post/$id': {
      id: '/feed/post/$id'
      path: '/post/$id'
      fullPath: '/feed/post/$id'
      preLoaderRoute: typeof FeedPostIdRouteImport
      parentRoute: typeof FeedRoute
    }
    '/dashboard/visit/new': {
      id: '/dashboard/visit/new'
      path: '/visit/new'
      fullPath: '/dashboard/visit/new'
      preLoaderRoute: typeof DashboardVisitNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/signature': {
      id: '/dashboard/settings/signature'
      path: '/settings/signature'
      fullPath: '/dashboard/settings/signature'
      preLoaderRoute: typeof DashboardSettingsSignatureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/followup': {
      id: '/dashboard/settings/followup'
      path: '/settings/followup'
      fullPath: '/dashboard/settings/followup'
      preLoaderRoute: typeof DashboardSettingsFollowupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/billing': {
      id: '/dashboard/settings/billing'
      path: '/settings/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patient/$id': {
      id: '/dashboard/patient/$id'
      path: '/patient/$id'
      fullPath: '/dashboard/patient/$id'
      preLoaderRoute: typeof DashboardPatientIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/d/$slug/contact.vcf': {
      id: '/d/$slug/contact.vcf'
      path: '/contact.vcf'
      fullPath: '/d/$slug/contact.vcf'
      preLoaderRoute: typeof DSlugContactDotvcfRouteImport
      parentRoute: typeof DSlugRoute
    }
    '/api/public/web-vitals': {
      id: '/api/public/web-vitals'
      path: '/api/public/web-vitals'
      fullPath: '/api/public/web-vitals'
      preLoaderRoute: typeof ApiPublicWebVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardEarningsRoute: typeof DashboardEarningsRoute
  DashboardExpensesRoute: typeof DashboardExpensesRoute
  DashboardPatientsRoute: typeof DashboardPatientsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardPatientIdRoute: typeof DashboardPatientIdRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsFollowupRoute: typeof DashboardSettingsFollowupRoute
  DashboardSettingsSignatureRoute: typeof DashboardSettingsSignatureRoute
  DashboardVisitNewRoute: typeof DashboardVisitNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardEarningsRoute: DashboardEarningsRoute,
  DashboardExpensesRoute: DashboardExpensesRoute,
  DashboardPatientsRoute: DashboardPatientsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardPatientIdRoute: DashboardPatientIdRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsFollowupRoute: DashboardSettingsFollowupRoute,
  DashboardSettingsSignatureRoute: DashboardSettingsSignatureRoute,
  DashboardVisitNewRoute: DashboardVisitNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface FeedRouteChildren {
  FeedNewRoute: typeof FeedNewRoute
  FeedPostIdRoute: typeof FeedPostIdRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedNewRoute: FeedNewRoute,
  FeedPostIdRoute: FeedPostIdRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

interface ProfileRouteChildren {
  ProfileLabResultsRoute: typeof ProfileLabResultsRoute
  ProfileMedicalHistoryRoute: typeof ProfileMedicalHistoryRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileLabResultsRoute: ProfileLabResultsRoute,
  ProfileMedicalHistoryRoute: ProfileMedicalHistoryRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface DSlugRouteChildren {
  DSlugContactDotvcfRoute: typeof DSlugContactDotvcfRoute
}

const DSlugRouteChildren: DSlugRouteChildren = {
  DSlugContactDotvcfRoute: DSlugContactDotvcfRoute,
}

const DSlugRouteWithChildren = DSlugRoute._addFileChildren(DSlugRouteChildren)

interface SpecialtySlugRouteChildren {
  SpecialtySlugCityRoute: typeof SpecialtySlugCityRoute
}

const SpecialtySlugRouteChildren: SpecialtySlugRouteChildren = {
  SpecialtySlugCityRoute: SpecialtySlugCityRoute,
}

const SpecialtySlugRouteWithChildren = SpecialtySlugRoute._addFileChildren(
  SpecialtySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentsRoute: AppointmentsRoute,
  BillingRoute: BillingRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DoctorsRoute: DoctorsRoute,
  FeedRoute: FeedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  IndexnowKeyDottxtRoute: IndexnowKeyDottxtRoute,
  JoinDoctorRoute: JoinDoctorRoute,
  LoginRoute: LoginRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  MissingDrugsRoute: MissingDrugsRoute,
  NearbyRoute: NearbyRoute,
  PayRoute: PayRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapArticlesDotxmlRoute: SitemapArticlesDotxmlRoute,
  SitemapDoctorsDotxmlRoute: SitemapDoctorsDotxmlRoute,
  SitemapSpecialtiesDotxmlRoute: SitemapSpecialtiesDotxmlRoute,
  SitemapStaticDotxmlRoute: SitemapStaticDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SwDotjsRoute: SwDotjsRoute,
  TermsRoute: TermsRoute,
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminEmrRoute: AdminEmrRoute,
  AdminErrorsRoute: AdminErrorsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSeedDirectoryRoute: AdminSeedDirectoryRoute,
  AdminSubscriptionRequestsRoute: AdminSubscriptionRequestsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportTicketsRoute: AdminSupportTicketsRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  ConsultationIdRoute: ConsultationIdRoute,
  DSlugRoute: DSlugRouteWithChildren,
  DoctorIdRoute: DoctorIdRoute,
  DoctorFeedbackRoute: DoctorFeedbackRoute,
  DoctorSoloRoute: DoctorSoloRoute,
  DoctorSponsorshipRoute: DoctorSponsorshipRoute,
  DoctorVerificationRoute: DoctorVerificationRoute,
  MyQueueAppointmentIdRoute: MyQueueAppointmentIdRoute,
  PharmacyDashboardRoute: PharmacyDashboardRoute,
  PharmacyRegisterRoute: PharmacyRegisterRoute,
  QShortIdRoute: QShortIdRoute,
  ReceiptAppointmentIdRoute: ReceiptAppointmentIdRoute,
  RxIdRoute: RxIdRoute,
  SpecialtySlugRoute: SpecialtySlugRouteWithChildren,
  USlugRoute: USlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ApiPublicWebVitalsRoute: ApiPublicWebVitalsRoute,
  RxVerifyNumberRoute: RxVerifyNumberRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
